# Generated by Django 4.2.9 on 2024-02-06 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRegions',
        ),
    ]
