# Generated by Django 4.2.9 on 2024-02-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_user_preferred_language_user_receive_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Transgender')], default='F', max_length=20),
        ),
    ]
